proj/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import logout, login
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.conf import settings
from django.views.decorators.cache import cache_page, never_cache
from django.conf.urls.static import static

from dcf import views, feeds, sitemap
from dcf.api.routers import router

admin.autodiscover()

urlpatterns = [
    url(r'^$', views.SectionListView.as_view()),

    url(r'^new/$', never_cache(views.ItemCreateView.as_view()), name='item-new'),
    url(r'^edit/(?P<pk>\d+)/$', never_cache(views.ItemUpdateView.as_view()), name='item-edit'),

    # listings
    url(r'^(?P<pk>\d+)-(?P<slug>[-\w]+)/$', views.ItemDetailView.as_view(), name='item'),
    url(r'^group/(?P<pk>\d+)-(?P<slug>[-\w]+)/$', views.GroupDetail.as_view(), name='group'),

    url(r'^search/', views.SearchView.as_view(), name='search'),
    url(r'^robots\.txt$', cache_page(60 * 60)(views.RobotsView.as_view()), name='robots'),

    url(r'^sitemap\.xml$', sitemap_view, {'sitemaps': sitemap.sitemaps_dict}, name='sitemap'),
    url(r'^rss\.xml$', cache_page(60 * 15)(feeds.LatestItemFeed()), name='rss'),

    url(r'^user/$', views.MyItemsView.as_view(), name='my'),
    url(r'^user/profile/$', views.view_profile, name='profile'),
    url(r'^user/my/delete/(?P<pk>\d+)/$', views.ItemDeleteView.as_view(), name='my-delete'),

    # Authorization
    url(r'user/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^user/login/', login, name='login'),
    url(r'^user/logout/$', logout, name='logout'),

    # API
    url(r'^api/', include(router.urls)),

    #url(r'^admin/', include(admin.site.urls)),

    # userena

     url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('userena.urls')),
]

handler404 = views.page404
handler403 = views.page403
handler500 = views.page500

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dcf/models.py
# -*- coding:utf-8 -*-
from sorl.thumbnail import ImageField
from unidecode import unidecode

from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from django.contrib.auth.models import AbstractUser

#userena
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from userena.models import UserenaBaseProfile


class CustomUser(UserenaBaseProfile):
    user = models.OneToOneField(User,
                                unique=True,
                                verbose_name=_('user'),
                                related_name='custom_user')  # userena setting
    phone = models.CharField(_('phone'), max_length=30, null=True, blank=True)
    receive_news = models.BooleanField(_('receive news'), default=True, db_index=True)

    def allow_add_item(self):
        if self.item_set.count() > settings.DCF_ITEM_PER_USER_LIMIT:
            return False
        else:
            return True


class Section(models.Model):
    title = models.CharField(_('title'), max_length=100)

    def __unicode__(self):
        return self.title

    def count(self):
        return Item.objects.filter(is_active=True)\
            .filter(group__section=self).count()

    class Meta:
        verbose_name = _('section')
        verbose_name_plural = _('sections')


class Group(models.Model):
    slug = models.SlugField(blank=True, null=True)
    title = models.CharField(_('title'), max_length=100)
    section = models.ForeignKey('Section', verbose_name=_('section'))

    def __unicode__(self):
        return u'%s - %s' % (self.section.title, self.title)

    def count(self):
        return self.item_set.filter(is_active=True).count()

    class Meta:
        verbose_name = _('group')
        verbose_name_plural = _('groups')
        ordering = ['section__title', 'title', ]

    def get_title(self):
        return u'%s' % self.title

    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(unidecode(self.title))
        super(Group, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('group', kwargs={'pk': self.pk, 'slug': self.slug})


class Item(models.Model):
    slug = models.SlugField(blank=True, null=True, max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    group = models.ForeignKey(Group, verbose_name=_('group'))

    title = models.CharField(_('title'), max_length=100)
    description = models.TextField(_('description'))
    price = models.DecimalField(_('price'), max_digits=10, decimal_places=2)
    phone = models.CharField(_('phone'), max_length=30)
    is_active = models.BooleanField(_('display'), default=True, db_index=True)
    updated = models.DateTimeField(_('updated'), auto_now=True, db_index=True)
    posted = models.DateTimeField(_('posted'), auto_now_add=True)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        ordering = ('-updated', )

    def get_absolute_url(self):
        return reverse('item', kwargs={
            'pk': self.pk,
            'slug': self.slug
        })

    def get_title(self):
        return u'%s' % self.title

    def get_description(self):
        return u'%s' % self.description[:155]

    def get_keywords(self):
        # TODO need more optimal keywords selection
        return ",".join(set(self.description.split()))

    def get_related(self):
        # TODO Need more complicated related select
        return Item.objects.exclude(pk=self.pk)[:settings.DCF_RELATED_LIMIT]

    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(unidecode(self.title))
        super(Item, self).save(*args, **kwargs)


class Image(models.Model):
    item = models.ForeignKey(Item)
    file = ImageField(_('image'), upload_to='images')

dcf/forms.py
# -*- coding:utf-8 -*-
from django import forms
from django.utils.translation import ugettext as _

from dcf.models import Item, Group, Image, CustomUser


class SearchForm(forms.Form):
    group = forms.ModelChoiceField(label=_('Group'), queryset=Group.objects.all(), required=False)
    q = forms.CharField(required=False, label=_('Query'),)

    def filter_by(self):
        # TODO search using more than one field
        # TODO split query string and make seaprate search by words
        filters = {}
        if self.cleaned_data['group'] is not None:
            filters['group'] = self.cleaned_data['group']
        filters['description__icontains'] = self.cleaned_data['q']

        return filters


class ItemCreateEditForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('group', 'title', 'description', 'price', 'phone', 'is_active')


class AdImageForm(forms.ModelForm):
    class Meta:
        model = Image
        exclude = ('owner',)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('phone', )

dcf/views.py
# -*- coding:utf-8 -*-
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, ListView, DeleteView, TemplateView
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormMixin
from django.conf import settings

from dcf.models import Item, Image, Group, Section
from dcf.forms import ItemCreateEditForm, ProfileForm, SearchForm


class FilteredListView(FormMixin, ListView):
    def get_form_kwargs(self):
        return {
            'initial': self.get_initial(),
            'prefix': self.get_prefix(),
            'data': self.request.GET or None
        }

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()

        form = self.get_form(self.get_form_class())

        if form.is_valid():
            self.object_list = self.object_list.filter(**form.filter_by())

        context = self.get_context_data(form=form)
        return self.render_to_response(context)


class SectionListView(ListView):
    model = Section


class SearchView(FilteredListView):
    form_class = SearchForm
    queryset = Item.objects.filter(is_active=True)
    paginate_by = 10
    template_name = 'dcf/search.html'


class FormsetMixin(object):
    object = None

    def get(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def post(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        if form.is_valid() and formset.is_valid():
            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)

    def get_formset_class(self):
        return self.formset_class

    def get_formset(self, formset_class):
        return formset_class(**self.get_formset_kwargs())

    def get_formset_kwargs(self):
        kwargs = {
            'instance': self.object
        }
        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
                })
        return kwargs

    def form_valid(self, form, formset):
        self.object = form.save()
        formset.instance = self.object
        formset.save()
        if hasattr(self, 'get_success_message'):
            self.get_success_message(form)
        return redirect(self.object.get_absolute_url())

    def form_invalid(self, form, formset):
        return self.render_to_response(self.get_context_data(form=form, formset=formset))


class GroupDetail(SingleObjectMixin, ListView):
    paginate_by = settings.DCF_ITEM_PER_PAGE

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Group.objects.all())
        return super(GroupDetail, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GroupDetail, self).get_context_data(**kwargs)
        context['group'] = self.object
        return context

    def get_queryset(self):
        return self.object.item_set.all()


class ItemDetailView(DetailView):
    queryset = Item.objects.filter(is_active=True)


class ItemUpdateView(FormsetMixin, UpdateView):
    is_update_view = True
    model = Item
    form_class = ItemCreateEditForm
    formset_class = inlineformset_factory(Item, Image, extra=3, fields=('file', ))

    def get_object(self, *args, **kwargs):
        obj = super(ItemUpdateView, self).get_object(*args, **kwargs)
        if not obj.user == self.request.user and not self.request.user.is_superuser:
            raise PermissionDenied
        return obj

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ItemUpdateView, self).dispatch(*args, **kwargs)


class ItemCreateView(FormsetMixin, CreateView):
    is_update_view = False
    model = Item
    form_class = ItemCreateEditForm
    formset_class = inlineformset_factory(Item, Image, extra=3, fields=('file', ))

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        if not self.request.user.custom_user.allow_add_item():
            messages.error(self.request, _('You have reached the limit!'))
            return redirect(reverse('my'))

        return super(ItemCreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form, formset):

        form.instance.user = self.request.user
        form.save()

        return super(ItemCreateView, self).form_valid(form, formset)


class MyItemsView(ListView):
    template_name = 'dcf/user_item_list.html'

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MyItemsView, self).dispatch(*args, **kwargs)


class ItemDeleteView(DeleteView):
    model = Item
    success_url = reverse_lazy('my')

    def get_object(self, queryset=None):
        obj = super(ItemDeleteView, self).get_object()
        if not obj.user == self.request.user and not self.request.user.is_superuser:
            raise PermissionDenied
        return obj

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ItemDeleteView, self).dispatch(*args, **kwargs)


@login_required
def view_profile(request):
    if request.method == 'GET':
        form = ProfileForm(instance=request.user, initial={'email': request.user.email})
    else:
        form = ProfileForm(request.POST, instance=request.user)
        if form.is_valid():

            form.save()
            messages.success(request, _('Your profile settings was updated!'))

            return redirect(reverse('profile'))

    return render(request, 'dcf/profile.html', {'form': form})


class RobotsView(TemplateView):
    template_name = 'robots.txt'
    content_type = 'text/plain'


def page403(request):
    return render(request, '403.html', {}, status=403)


def page404(request):
    return render(request, '404.html', {}, status=404)


def page500(request):
    return render(request, '500.html', {}, status=500)

dcf/templates/dcf/admin_toolbar.inc.html
{% load i18n %}

{% if user.is_superuser %}
    <div class="row">
        <div class="col-lg-12">
            [<a href='{% url 'my-delete' item.pk %}'>{% trans "Delete" %}</a>]
            [<a href='{% url 'item-edit' item.pk %}'>{% trans "Edit" %}</a>]
        </div>
    </div>
{% endif %}

dcf/templates/dcf/form_pagination.inc.html
{% load i18n %}

<nav>
    <ul class="pagination">
        <li>
            <button class="btn"
                name="page"
                value="{% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}"
                type="submit"
                {% if not page_obj.has_previous %}
                disabled="disabled"
                {% endif %}>
                {% trans "Prev" %}
            </button>
        </li>

        <li>
            <button class="btn"
                name="page"
                value="{% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}"
                type="submit"
                {% if not page_obj.has_next %}
                disabled="disabled"
                {% endif %}>
               {% trans "Next" %}
            </button>
        </li>
    </ul>
</nav>

dcf/templates/dcf/item_confirm_delete.html
{% extends "_base.html" %}

{% load humanize thumbnail i18n %}

{% block title %}{% trans "Delete" %} {{ object.get_title }}{% endblock title %}

{% block body %}
    <div class="row">
        <div class="col-lg-12">
            <form action="" method="post">
                {% csrf_token %}
                <p>
                    {% trans "Are you sure you want to delete" %}
                    <a href="{{ object.get_absolute_url }}">{{ object }}</a>?
                </p>
                <input type="submit" value="{% trans "Confirm" %}" class="btn btn-danger">
            </form>
        </div>
    </div>
{% endblock %}

dcf/templates/dcf/item_detail.html
{% extends "_base.html" %}

{% load humanize thumbnail i18n %}

{% block title %}{{ object.get_title }}{% endblock title %}
{% block meta_description %}{{ object.get_description }}{% endblock meta_description %}
{% block meta_keywords %}{{ object.get_keywords }}{% endblock meta_keywords %}

{% block meta_og %}
    <meta property="og:url" content="{{ request.scheme }}://{{ request.get_host }}{{ object.get_absolute_url }}" />
    <meta property="og:title" content="{{object.get_title}}" />
    <meta property="og:description" content="{{ object.get_description }}" />
    {% for img in object.image_set.all %}
        {% thumbnail img.file "640x480" padding=True as im %}
            <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{{ im.url }}" />
        {% endthumbnail %}
    {% endfor %}
{% endblock %}

{% block body %}
    {% include "dcf/admin_toolbar.inc.html" %}

    <div class="row">
        <div class="col-lg-12">
            <a href='{{ object.group.get_absolute_url }}'>{{ object.group }}</a>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-9">
            <h1>{{ object.title }}</h1>
        </div>
        <div class="col-lg-3">
            <h2>{{ object.price|default:"" }}</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            {{ object.description|linebreaksbr }}
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">

            {% for img in object.image_set.all %}

                {% thumbnail img.file "150x150" crop="center" as im %}
                    <a href='{{img.file.url}}' data-lightbox="lightbox[{{object.id}}]" title="{{object.title}}">
                        <img src='{{ im.url}}' alt='{{object.title}}' title='{{object.title}}' width="{{ im.width }}" height="{{ im.height }}" class="img-rounded" />
                    </a>
                {% endthumbnail %}

            {% endfor %}

        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <hr />
            {% if DCF_LOGIN_TO_CONTACT and not user.is_authenticated %}
                {% trans "Please" %} <a href='{% url 'login' %}'>{% trans "login" %}</a> {%  trans "to see contact information." %}
            {% else %}
                {% trans "Phone" %}: {{ object.phone }}
            {% endif %}
        </div>
    </div>

    <div class="row">

        <div class="col-lg-12">
            <hr />
        </div>

        {% for item in object.get_related %}
            <div class="col-md-2">
                {% if item.image_set.all %}
                    {% with item.image_set.all.0 as img %}

                        {% thumbnail img.file "70x70" crop="center" as im %}
                            <a href='{{item.get_absolute_url}}' title="{{item.get_title}}">
                                <img src='{{im.url}}' alt='{{item.title}}' title='{{item.title}}' width="{{ im.width }}" height="{{ im.height }}" class="img-rounded" />
                            </a>
                        {% endthumbnail %}

                    {% endwith %}
                {% endif %}
                <br/>
                <a href='{{item.get_absolute_url}}' title="{{item.get_title}}">{{item.title|truncatewords:3}}</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

dcf/templates/dcf/item_form.html
{% extends "_base.html" %}

{% load i18n bootstrap %}

{% block title %}{% if form.instance.pk %}{% trans "Edit" %}{% else %}{% trans "Add" %}{% endif %} {% trans "item" %}{% endblock title %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <form enctype="multipart/form-data" method='post' role="form">
                {{ formset.management_form }}

                {% csrf_token %}

                {{ form|bootstrap }}

                {% for form in formset %}
                    {{ form|bootstrap }}
                {% endfor %}
                <input type='submit' class="btn" value='{% trans "Save" %}'>
            </form>
        </div>
    </div>
{% endblock body %}

dcf/templates/dcf/item_list.html
{% extends "_base.html" %}

{% block title %}{{ object }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-lg-12">
            <h1>
                <a href="{{ object.get_absolute_url }}" title="{{ object.get_title }}">
                    {{ object }}
                </a>
            </h1>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            {% include "dcf/item_list.inc.html" %}
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            {% include "dcf/list_pagination.inc.html" %}
        </div>
    </div>
{% endblock body %}

dcf/templates/dcf/item_list.inc.html
{% load humanize thumbnail i18n%}

{% for object in object_list %}
    {% if forloop.first  %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <td></td>
                    <td>{% trans "Price" %}</td>
                </tr>
            </thead>
            <tbody>
    {%  endif %}
                <tr>
                    <td>
                        {% if object.image_set.all|length > 0 %}
                            {% thumbnail object.image_set.all.0.file "45x45" crop="center" as im %}
                                <a href='{{ object.get_absolute_url }}' title="{{object.get_title}}">
                                    <img src='{{im.url}}' alt='{{object.title}}' title='{{object.title}}'  width="{{ im.width }}" height="{{ im.height }}" class="img-rounded" />
                                    {% if object.image_set.all|length > 1 %}
                                        <span class="badge badge-notify" title="{{ object.image_set.count|add:-1 }} {% trans 'more photos available' %}"> + {{ object.image_set.count|add:-1}}</span>
                                    {% endif %}
                                </a>
                            {% endthumbnail %}
                        {% endif %}
                        <a href='{{ object.get_absolute_url }}' title='{{object.get_title}}'>
                            {{object.title}}
                        </a>
                    </td>
                    <td>
                        {{ object.price|default:"" }}
                    </td>
                </tr>
{% if forloop.last  %}
        </tbody>
    </table>
{% endif %}

{% empty %}
    <p>
        {% trans "No item here yet." %}
        <a href="{% url 'item-new' %}">{% trans "Add one now!" %}</a>
    </p>
{% endfor %}

dcf/templates/dcf/list_pagination.inc.html
{% load i18n %}

<nav>
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}">{% trans "Prev" %}</a>
            </li>
        {% endif %}
        {% if page_obj.has_next %}
            <li>
                <a href="?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a>
            </li>
        {% endif %}
    </ul>
</nav>

dcf/templates/dcf/profile.html
{% extends "_base.html" %}

{% load i18n bootstrap %}

{% block title %}{% trans "Profile" %}{% endblock title %}

{% block body %}
    <div class="row marketing">
        <div class="col-lg-12">
            <form method="post" role="form">
                {% csrf_token %}
                {{ form|bootstrap }}
                <input type="submit" value="{% trans "Update" %}" class="btn">
            </form>
        </div>
    </div>
{% endblock %}

dcf/templates/dcf/search.html
{% extends "_base.html" %}

{% load i18n bootstrap %}

{% block title %}
    {% if form.q.value  %}{% trans "Search results for query" %} "{{ form.q.value }}" {% else %}{% trans "Search" %}{% endif %}
{% endblock title %}

{% block body %}
    <div class="row">
        <div class="col-lg-6">
            <h3>{% trans "Search" %}</h3>
            <form method="get" role="form">
                {{ form|bootstrap }}
                <button type="submit" class="btn" name="page" value="1">{% trans "Search" %}</button>
                {% if object_list|length %}
                    {% include 'dcf/form_pagination.inc.html' %}
                {% endif %}
            </form>
        </div>
    </div>
    <div>
        <hr/>
        {% if object_list|length %}
            <h4>{% blocktrans %}Search results ({{ paginator.count }} items found):{% endblocktrans %}</h4>
            {% include "dcf/item_list.inc.html" with item=object %}
        {% else %}
            <h4>{% trans "Not found" %}</h4>
        {% endif %}
    </div>
{% endblock %}

dcf/templates/dcf/section_list.html
{% extends "_base.html" %}

{% block title %}{{DCF_SITE_NAME}}{% endblock title %}

{% block body %}
    {% for object in object_list %}
        {% if forloop.first %}
            <div class="row marketing">
        {% endif %}

        <div class="col-lg-4">
            <h4>{{ object }}</h4>

            {% for group in object.group_set.all %}
                {% if group.count > 0 %}
                    <a href='{{ group.get_absolute_url }}' title="{{ group.get_title }}">
                        {{group.title}} [{{group.count}}]<br/>
                    </a>
                {% endif %}
            {% endfor %}
        </div>

        {% if forloop.counter|divisibleby:3 or forloop.last %}
            </div>
            {% if not forloop.last %}
                <div class="row marketing">
            {% endif %}
        {% endif %}
    {% endfor %}
{% endblock %}

dcf/templates/dcf/user_item_list.html
{% extends "_base.html" %}

{% load humanize i18n %}

{% block title %}{%  trans "My items" %}{% endblock title %}

{% block body %}
    <div class="row">
        <div class="col-lg-12">
            <h2>{%  trans "My items" %}</h2>
            {% for object in object_list %}
                {% if forloop.first  %}
                    <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <td>{%  trans "Group" %}</td>
                        <td>{%  trans "Update" %}</td>
                        <td>{%  trans "Link" %}</td>
                        <td>{%  trans "Price" %}</td>
                        <td>{%  trans "Posted" %}</td>
                        <td>{%  trans "Delete" %}</td>
                    </tr>
                    </thead>
                {%  endif %}
            <tr>
                <td><a href='{{ object.group.get_absolute_url }}'>{{object.group}}</a></td>
                <td><a href='{% url 'item-edit' object.pk %}' title='{%  trans "Edit item" %}'>{{object.title}}</a></td>
                <td><a href='{{ object.get_absolute_url }}' title='{%  trans "Open item" %}'>{%  trans "Open" %}</a></td>
                <td>{{object.price|intcomma}}</td>
                <td>{{object.posted|date:"d.m.Y"}}</td>
                <td><a href='{% url 'my-delete' object.id %}'>{%  trans "Delete" %}</a></td>
            </tr>

            {% if forloop.last  %}
                </table>
            {% endif %}

            {% empty %}
                <p>
                    {%  trans "You have no items to show." %}
                    <a href="{% url 'item-new' %}">{% trans "Add one now!" %}</a>
                </p>
            {% endfor %}
        </div>
    </div>
{% endblock %}